[package]
name = "go2url-icu"
version = "0.1.0"
authors = ["Alex Black <wa7@sa34.cx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
